### ISSUE TITLE
Failed to parse results file

### ISSUE THREAD

**Issue by Eldadc** [ETCLabs/unity-test-parser#2]
Hi,

I am trying to convert results file from Unity UT results.
I am running mu Unity UT from Jenkins , I need a results file.
Error 
"No Test were Found" 
OF course the results file is created.

My results file format is : 
(1)Unit Test ...

(2) Unit Test ...

Thanks

**Comment by samkearney** [comment]
Hi @Eldadc ,

As stated in the README, this utility can parse Unity test output in one of the following formats:

Basic Unity test output:
```
path/to/file.c:100:test_name:PASS
path/to/file.c:101:other_test_name:FAIL: Expected 1 Was 2
```

Unity test output using the Unity Fixture add-on:
```
TEST(group, test_name)path/to/file.c:100::FAIL: Expected 1 Was 2
```

If your test output is not printed in one of these two formats, this utility will not help you.

**Comment by Eldadc** [comment]
Thanks on the quick response.
I undersrand.
Do you know how to control unity output in order to create supported results log.

Thanks

**Comment by samkearney** [comment]
I've never seen any other output from Unity other than the two forms in my comment. I wasn't aware it could produce output in other formats. For example, the first format is what is demonstrated on the [website](https://www.throwtheswitch.org/unity) (see "How Unity Works")

It's possible that the output has changed since the last version of this utility was released in Nov. 2019. Can you provide the complete test output you're seeing?

**Comment by songg10** [comment]
Hi, 
I am trying to parse an output file which look like this:
```
test/TestProductionCode.c:20:test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode:PASS
test/TestProductionCode.c:33:test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken:FAIL: Expected 1 Was 0
test/TestProductionCode.c:41:test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue:PASS
test/TestProductionCode.c:51:test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain:PASS
test/TestProductionCode.c:61:test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed:FAIL: Expected 0x00001234 Was 0x00005A5A
```

and it raises a ValueError exception:
```
Traceback (most recent call last):
  File "test_parser.py", line 12, in <module>
    main()
  File "test_parser.py", line 6, in main
    results = unity_test_parser.TestResult(result_file.read(), unity_test_parser.UNITY_BASIC)
  File "/home/song10/.local/lib/python3.8/site-packages/unity_test_parser.py", line 72, in __init__
    raise ValueError("result must be one of {}.".format(_TEST_RESULT_ENUM))
ValueError: result must be one of ['PASS', 'FAIL', 'IGNORE'].
```

This is the python script I wrote to parse the result:
```
import unity_test_parser
import junit_xml

def main():
  with open("output.txt", "r") as result_file:
    results = unity_test_parser.TestResult(result_file.read(), unity_test_parser.UNITY_BASIC)

    with open("report.xml", "w") as out_file:
      junit_xml.TestSuite.to_file(out_file, [results.to_junit()])

if __name__ == "__main__":
  main()
```
Could you let me know what I have done wrong because my output looks exactly like the sample output file.
